#
# $Id$
#

include $(ROOT_DIR)/Makefile.pre

CODE_SUBDIRS = .
	

################################################
####   source file 
################################################

SRC = \
    libCgi.c \
    libCgiBase64.c \
    libCgiCookie.c \
    libCgiError.c \
    libCgiGeneral.c \
    libCgiList.c \
    libCgiMd5.c \
    libCgiSession.c \
    libCgiString.c \
    libCgiUpload.c \


TARGET_LIB:=libcgi
TARGET_LIB_SHARED:=$(TARGET_LIB).so
TARGET_LIB_STATIC:=$(TARGET_LIB).a

include $(ROOT_DIR)/Makefile.post

